-- История запросов клиентов и запусков анализа (v2).
-- 1) client_requests: что запросил клиент
-- 2) analysis_runs: конкретный прогон (competitive/market) по запросу
-- 3) run_id + conclusion в доменных таблицах

-- ========== 1. Таблицы истории ==========

create table if not exists public.client_requests (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  query_text text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.analysis_runs (
  id bigint generated by default as identity primary key,
  request_id bigint not null references public.client_requests(id) on delete cascade,
  report_type text not null default '', -- competitive | market
  source_csv text not null default '',
  top_n int not null default 0,
  perplexity_model text not null default '',
  created_at timestamptz not null default now()
);

create index if not exists idx_client_requests_user_id on public.client_requests(user_id);
create index if not exists idx_analysis_runs_request_id on public.analysis_runs(request_id);
create index if not exists idx_analysis_runs_created_at on public.analysis_runs(created_at);

alter table public.client_requests enable row level security;
alter table public.analysis_runs enable row level security;

-- Пользователь видит только свои запросы/запуски
drop policy if exists "Users can read own requests" on public.client_requests;
create policy "Users can read own requests"
  on public.client_requests for select
  using (auth.uid() = user_id);

drop policy if exists "Users can create own requests" on public.client_requests;
create policy "Users can create own requests"
  on public.client_requests for insert
  with check (auth.uid() = user_id);

drop policy if exists "Users can read own runs" on public.analysis_runs;
create policy "Users can read own runs"
  on public.analysis_runs for select
  using (
    exists (
      select 1
      from public.client_requests cr
      where cr.id = analysis_runs.request_id
        and cr.user_id = auth.uid()
    )
  );

-- ========== 2. Расширение доменных таблиц ==========

-- Новые колонки заключений (выводов) из блоков 1..5
alter table public.restaurants
  add column if not exists conclusion text not null default '';

alter table public.menus
  add column if not exists conclusion text not null default '';

alter table public.reviews
  add column if not exists conclusion text not null default '';

alter table public.marketing
  add column if not exists conclusion text not null default '';

alter table public.technical_analysis
  add column if not exists conclusion text not null default '';

-- Привязка всех данных к run
alter table public.restaurants add column if not exists run_id bigint;
alter table public.menus add column if not exists run_id bigint;
alter table public.menu_items add column if not exists run_id bigint;
alter table public.reviews add column if not exists run_id bigint;
alter table public.marketing add column if not exists run_id bigint;
alter table public.marketing_socials add column if not exists run_id bigint;
alter table public.marketing_loyalty add column if not exists run_id bigint;
alter table public.technical_analysis add column if not exists run_id bigint;
alter table public.strategic_report add column if not exists run_id bigint;

-- FK (создаём безопасно через DO-блок, чтобы не падать при повторном прогоне)
do $$
begin
  if not exists (select 1 from information_schema.table_constraints where constraint_name = 'restaurants_run_id_fkey') then
    alter table public.restaurants add constraint restaurants_run_id_fkey foreign key (run_id) references public.analysis_runs(id) on delete cascade;
  end if;
  if not exists (select 1 from information_schema.table_constraints where constraint_name = 'menus_run_id_fkey') then
    alter table public.menus add constraint menus_run_id_fkey foreign key (run_id) references public.analysis_runs(id) on delete cascade;
  end if;
  if not exists (select 1 from information_schema.table_constraints where constraint_name = 'menu_items_run_id_fkey') then
    alter table public.menu_items add constraint menu_items_run_id_fkey foreign key (run_id) references public.analysis_runs(id) on delete cascade;
  end if;
  if not exists (select 1 from information_schema.table_constraints where constraint_name = 'reviews_run_id_fkey') then
    alter table public.reviews add constraint reviews_run_id_fkey foreign key (run_id) references public.analysis_runs(id) on delete cascade;
  end if;
  if not exists (select 1 from information_schema.table_constraints where constraint_name = 'marketing_run_id_fkey') then
    alter table public.marketing add constraint marketing_run_id_fkey foreign key (run_id) references public.analysis_runs(id) on delete cascade;
  end if;
  if not exists (select 1 from information_schema.table_constraints where constraint_name = 'marketing_socials_run_id_fkey') then
    alter table public.marketing_socials add constraint marketing_socials_run_id_fkey foreign key (run_id) references public.analysis_runs(id) on delete cascade;
  end if;
  if not exists (select 1 from information_schema.table_constraints where constraint_name = 'marketing_loyalty_run_id_fkey') then
    alter table public.marketing_loyalty add constraint marketing_loyalty_run_id_fkey foreign key (run_id) references public.analysis_runs(id) on delete cascade;
  end if;
  if not exists (select 1 from information_schema.table_constraints where constraint_name = 'technical_analysis_run_id_fkey') then
    alter table public.technical_analysis add constraint technical_analysis_run_id_fkey foreign key (run_id) references public.analysis_runs(id) on delete cascade;
  end if;
  if not exists (select 1 from information_schema.table_constraints where constraint_name = 'strategic_report_run_id_fkey') then
    alter table public.strategic_report add constraint strategic_report_run_id_fkey foreign key (run_id) references public.analysis_runs(id) on delete cascade;
  end if;
end $$;

create index if not exists idx_restaurants_run_id on public.restaurants(run_id);
create index if not exists idx_menus_run_id on public.menus(run_id);
create index if not exists idx_menu_items_run_id on public.menu_items(run_id);
create index if not exists idx_reviews_run_id on public.reviews(run_id);
create index if not exists idx_marketing_run_id on public.marketing(run_id);
create index if not exists idx_marketing_socials_run_id on public.marketing_socials(run_id);
create index if not exists idx_marketing_loyalty_run_id on public.marketing_loyalty(run_id);
create index if not exists idx_technical_analysis_run_id on public.technical_analysis(run_id);
create index if not exists idx_strategic_report_run_id on public.strategic_report(run_id);

-- ========== 3. RLS для доменных таблиц по run ==========
-- Примечание: ранее в проекте были политики "Allow all for anon".
-- Здесь добавляем политики для authenticated. Если хотите закрыть anon полностью — удалите старые политики вручную.

create or replace function public.can_access_run(rid bigint)
returns boolean
language sql
stable
as $$
  select exists (
    select 1
    from public.analysis_runs ar
    join public.client_requests cr on cr.id = ar.request_id
    where ar.id = rid and cr.user_id = auth.uid()
  );
$$;

-- restaurants
drop policy if exists "Users can read restaurants by run" on public.restaurants;
create policy "Users can read restaurants by run"
  on public.restaurants for select
  to authenticated
  using (public.can_access_run(run_id));

-- menus
drop policy if exists "Users can read menus by run" on public.menus;
create policy "Users can read menus by run"
  on public.menus for select
  to authenticated
  using (public.can_access_run(run_id));

-- menu_items
drop policy if exists "Users can read menu_items by run" on public.menu_items;
create policy "Users can read menu_items by run"
  on public.menu_items for select
  to authenticated
  using (public.can_access_run(run_id));

-- reviews
drop policy if exists "Users can read reviews by run" on public.reviews;
create policy "Users can read reviews by run"
  on public.reviews for select
  to authenticated
  using (public.can_access_run(run_id));

-- marketing
drop policy if exists "Users can read marketing by run" on public.marketing;
create policy "Users can read marketing by run"
  on public.marketing for select
  to authenticated
  using (public.can_access_run(run_id));

-- marketing_socials
drop policy if exists "Users can read marketing_socials by run" on public.marketing_socials;
create policy "Users can read marketing_socials by run"
  on public.marketing_socials for select
  to authenticated
  using (public.can_access_run(run_id));

-- marketing_loyalty
drop policy if exists "Users can read marketing_loyalty by run" on public.marketing_loyalty;
create policy "Users can read marketing_loyalty by run"
  on public.marketing_loyalty for select
  to authenticated
  using (public.can_access_run(run_id));

-- technical_analysis
drop policy if exists "Users can read technical_analysis by run" on public.technical_analysis;
create policy "Users can read technical_analysis by run"
  on public.technical_analysis for select
  to authenticated
  using (public.can_access_run(run_id));

-- strategic_report
drop policy if exists "Users can read strategic_report by run" on public.strategic_report;
create policy "Users can read strategic_report by run"
  on public.strategic_report for select
  to authenticated
  using (public.can_access_run(run_id));

