alter table public.subscriptions
  add column if not exists is_lifetime boolean not null default false,
  add column if not exists payment_provider text not null default '',
  add column if not exists external_payment_id text not null default '';

create table if not exists public.payments (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  plan_code text not null,
  amount_rub int not null default 0,
  period_days int not null default 30,
  status text not null default 'pending', -- pending|paid|failed|canceled
  provider text not null default 'stripe',
  provider_payment_id text not null default '',
  checkout_url text not null default '',
  created_at timestamptz not null default now(),
  paid_at timestamptz
);

create index if not exists idx_payments_user_id on public.payments(user_id);
create index if not exists idx_payments_status on public.payments(status);

alter table public.payments enable row level security;

drop policy if exists "Users can read own payments" on public.payments;
create policy "Users can read own payments"
  on public.payments for select
  using (auth.uid() = user_id);

drop policy if exists "Users can create own payments" on public.payments;
create policy "Users can create own payments"
  on public.payments for insert
  with check (auth.uid() = user_id);

-- Ensure specified user has perpetual active subscription
insert into public.subscriptions (user_id, plan_name, is_active, is_lifetime, started_at, expires_at, payment_provider, external_payment_id)
values (
  'cf933749-6d7a-4b12-8df2-6892912a0910',
  'Энтерпрайз',
  true,
  true,
  current_date,
  null,
  'manual',
  'lifetime-seed'
)
on conflict do nothing;

