-- Таблицы для дашборда MarketScope (рестораны, меню, отзывы, маркетинг, теханализ, отчёты).
-- Выполните в SQL Editor в Supabase Dashboard или: supabase db push

create table if not exists public.restaurants (
  id bigint generated by default as identity primary key,
  name text not null default '',
  address text not null default '',
  type text not null default '',
  cuisine text not null default '',
  avg_check numeric not null default 0,
  description text not null default '',
  link text not null default '',
  cosine_score numeric not null default 0,
  site text not null default '',
  delivery boolean not null default false,
  working_hours text not null default ''
);

create table if not exists public.menus (
  id bigint generated by default as identity primary key,
  restaurant_id bigint not null references public.restaurants(id) on delete cascade,
  status text not null default '',
  menu_urls text[] default '{}',
  items_count int not null default 0,
  has_kids_menu boolean not null default false,
  categories text[] default '{}'
);

create table if not exists public.menu_items (
  id bigint generated by default as identity primary key,
  menu_id bigint not null references public.menus(id) on delete cascade,
  category text not null default '',
  name text not null default '',
  price numeric not null default 0
);

create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  restaurant_id bigint not null references public.restaurants(id) on delete cascade,
  summary_mode text not null default '',
  reviews_count int not null default 0,
  general_info text not null default '',
  positive text not null default '',
  negative text not null default ''
);

create table if not exists public.marketing (
  id bigint generated by default as identity primary key,
  restaurant_id bigint not null references public.restaurants(id) on delete cascade,
  site text not null default ''
);

create table if not exists public.marketing_socials (
  id bigint generated by default as identity primary key,
  marketing_id bigint not null references public.marketing(id) on delete cascade,
  network text not null default '',
  url text not null default ''
);

create table if not exists public.marketing_loyalty (
  id bigint generated by default as identity primary key,
  marketing_id bigint not null references public.marketing(id) on delete cascade,
  has_loyalty boolean not null default false,
  loyalty_name text not null default '',
  loyalty_format text not null default '',
  loyalty_cost_per_point numeric not null default 0,
  loyalty_how_to_earn text not null default ''
);

create table if not exists public.technical_analysis (
  id bigint generated by default as identity primary key,
  restaurant_id bigint not null references public.restaurants(id) on delete cascade,
  url text not null default '',
  status_code int not null default 0,
  load_time_sec numeric not null default 0,
  mobile_load_time_sec numeric not null default 0,
  page_size_kb numeric not null default 0,
  title text not null default '',
  meta_description text not null default '',
  https boolean not null default false,
  has_viewport boolean not null default false,
  error text not null default ''
);

create table if not exists public.strategic_report (
  id bigint generated by default as identity primary key,
  restaurant_id bigint not null references public.restaurants(id) on delete cascade,
  block1 text not null default '',
  block2 text not null default '',
  block3 text not null default '',
  block4 text not null default '',
  block5 text not null default '',
  report_md text not null default '',
  positioning text not null default '',
  menu text not null default '',
  reviews text not null default '',
  marketing text not null default '',
  technical_part text not null default '',
  business_recommendations text not null default '',
  reference_info text not null default ''
);

-- Доступ для anon (если используете RLS — настройте политики отдельно)
alter table public.restaurants enable row level security;
alter table public.menus enable row level security;
alter table public.menu_items enable row level security;
alter table public.reviews enable row level security;
alter table public.marketing enable row level security;
alter table public.marketing_socials enable row level security;
alter table public.marketing_loyalty enable row level security;
alter table public.technical_analysis enable row level security;
alter table public.strategic_report enable row level security;

create policy "Allow all for anon" on public.restaurants for all to anon using (true) with check (true);
create policy "Allow all for anon" on public.menus for all to anon using (true) with check (true);
create policy "Allow all for anon" on public.menu_items for all to anon using (true) with check (true);
create policy "Allow all for anon" on public.reviews for all to anon using (true) with check (true);
create policy "Allow all for anon" on public.marketing for all to anon using (true) with check (true);
create policy "Allow all for anon" on public.marketing_socials for all to anon using (true) with check (true);
create policy "Allow all for anon" on public.marketing_loyalty for all to anon using (true) with check (true);
create policy "Allow all for anon" on public.technical_analysis for all to anon using (true) with check (true);
create policy "Allow all for anon" on public.strategic_report for all to anon using (true) with check (true);
